object AffogatoModules {
  const val sample = ":sample"
  const val coreKtx = ":affogato-core-ktx"
  const val coroutinesAndroid = ":affogato-coroutines-android"
  const val coroutinesCore = ":affogato-coroutines-core"
  const val hiltBinding = ":affogato-hilt-binding"
  const val hiltBindingProcessor = ":affogato-hilt-binding-processor"
  const val loggerAndroid = ":affogato-logger-android"
  const val MetricaKtx = ":affogato-metrica-ktx"
  const val OkhttpAndroid = ":affogato-okhttp-android"
  const val pdfViewer = ":affogato-pdf-viewer"
  const val structure = ":affogato-structure"
  const val unit = ":affogato-unit"
  const val unitProcessor = ":affogato-unit-processor"
}
